
## If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title: Datarian
email: datarian@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
baseurl: "/blog"
url: "https://datarian-kr.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: datarian
github_username:  datarian-kr

# Build settings
theme: minima
plugins:
  - jekyll-feed
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed


# About
author:
  name:         datarian
  url:          https://datarian-kr.github.io
  email:        datarian@gmail.com  
  github:       datarian-kr
  twitter:      datarian

# Custom vars
version:        1.0.0
github:
  repo:         https://github.com/datarian-kr/blog



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
